// 30-Day Summer Training Program data — Hindustan United Sports
// (extracted verbatim from the academy program prototype)

const WEEKS = {
  1: { theme: 'Foundation Intensity', emoji: '🏗️', desc: 'Build a bulletproof base — stamina, ball mastery, movement patterns, mental habits.' },
  2: { theme: 'Speed & Skill', emoji: '⚡', desc: 'Explosive first step, advanced dribbling, 1v1 confidence, and sharper decision-making.' },
  3: { theme: 'Power & Tactics', emoji: '🎯', desc: 'Strength endurance, tactical positioning, set pieces, and elite mental resilience.' },
  4: { theme: 'Elite Performance', emoji: '🏆', desc: 'Match-intensity sessions, technical mastery under fatigue, complete player mindset.' }
};

const DAY_LABELS = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];

const ALL_DAYS = {
  // ════ WEEK 1 ════
  '1-1': { rest: false, label: 'Mon', focus: 'Activation + Ball Mastery + Aerobic Base', tasks: [
    { id:'t1', pillar:'Physical', title:'Morning activation & warm-up', dur:15, sets:'', desc:'20 jumping jacks → 15 high knees → 10 arm circles → 10 hip rotations → dynamic leg swings (10 each leg) → 5 burpees. No equipment. Activates entire body for training.', xp:20 },
    { id:'t2', pillar:'Technical', title:'Ball mastery — foundations', dur:20, sets:'3 sets', desc:'Sole rolls (50 touches each foot) → inside/outside toe taps (1 min) → V-pull-backs (30 reps) → scissors in place (20 each direction). Small space fine. Focus: clean touch, no rushes.', xp:30 },
    { id:'t3', pillar:'Physical', title:'Speed & agility bodyweight', dur:20, sets:'4 rounds', desc:'Sprint in place max effort 30 sec → rest 15 sec → lateral shuffle steps 30 sec → rest 15 sec → explosive jump squats 10 reps → rest 30 sec. Repeat 4 rounds.', xp:30 },
    { id:'t4', pillar:'Technical', title:'Wall passing or juggling (20 min)', dur:20, sets:'', desc:'Wall: 1-touch passes 100 reps each foot, then 2-touch control. No wall: juggling (target 50 consecutive), thigh-knee-foot combos, air control drops. Stay focused every touch.', xp:35 },
    { id:'t5', pillar:'Mental', title:'Visualization session', dur:10, sets:'', desc:'Close eyes. Visualize yourself in a match: receiving under pressure, making the right decision, executing a skill perfectly, scoring. Run 3 full match scenarios mentally. Pros do this daily.', xp:15 },
    { id:'t6', pillar:'Tactical', title:'Positions off the ball — study', dur:10, sets:'', desc:'Watch 10 min of pro match. Focus on ONE player in your position. Track: where they move WITHOUT ball, when they check shoulders, how they angle body before receiving. Write 3 observations.', xp:20 },
  ]},
  '1-2': { rest: false, label: 'Tue', focus: 'Dribbling + Lower Body Strength + First Touch', tasks: [
    { id:'t1', pillar:'Physical', title:'Warm-up + explosive activation', dur:15, sets:'', desc:'Jog in place 2 min → high knees 1 min → butt kicks 1 min → 10 squat jumps → 10 long jumps in place → 5 burpees → 10 push-ups. Primes fast-twitch muscles.', xp:20 },
    { id:'t2', pillar:'Technical', title:'Dribbling — cone-free circuits', dur:25, sets:'', desc:'Use shoes/bottles as cones. Slalom dribbling 10 reps → cut-inside pull-back combo (30 reps) → step-over drill (20 each direction) → Cruyff turn (20 reps) → elastico attempts (10 min). Clean touches, not speed.', xp:40 },
    { id:'t3', pillar:'Physical', title:'Strength circuit — lower body', dur:20, sets:'3 rounds', desc:'20 squats → 15 lunges each leg → 20 calf raises → 10 single-leg squats each side → 30 sec wall sit → 10 jump squats. Rest 60 sec between rounds. Explosive legs = football weapon.', xp:35 },
    { id:'t4', pillar:'Technical', title:'First touch mastery', dur:15, sets:'', desc:'Throw ball up, control with right foot instep 30 times → left foot 30 times → chest control (20) → thigh (20) → full sequence: throw → chest → thigh → foot. Slow and precise wins.', xp:25 },
    { id:'t5', pillar:'Mental', title:'Focus & pressure juggling', dur:10, sets:'', desc:'Set 5-min timer. Juggle. Every time you drop: 5 push-ups, restart count. Track highest run. This trains concentration under self-imposed pressure — exactly like a match.', xp:20 },
    { id:'t6', pillar:'Tactical', title:'Defensive shape — awareness drill', dur:10, sets:'', desc:'How does your team defend as a unit? Study pressing triggers: when to press high, when to drop. Draw on paper: your defensive position out of possession. Compare 1-4-4-2 vs 1-4-3-3 shape.', xp:20 },
  ]},
  '1-3': { rest: false, label: 'Wed', focus: 'Stamina + Juggling + Core + Tactical Movement', tasks: [
    { id:'t1', pillar:'Physical', title:'Stamina run — small space protocol', dur:30, sets:'', desc:'30 min continuous: 2 min jog in place → 1 min high knees → 1 min shadow dribbling → 30 sec sprint in place. Cycle without stopping. Football-specific aerobic conditioning.', xp:40 },
    { id:'t2', pillar:'Technical', title:'Juggling progression', dur:20, sets:'', desc:'Right foot only (50) → left foot only (50) → alternating (100 target) → head (20) → chest trap-juggle combos (15 reps). Track personal best each session. This is the week 1 baseline.', xp:35 },
    { id:'t3', pillar:'Mental', title:'Goal setting & match mindset', dur:10, sets:'', desc:'Write: (1) Your 3-month football goal (2) One technical weakness to fix this month (3) Pre-match mental routine. Building this habit now creates consistency under pressure.', xp:15 },
    { id:'t4', pillar:'Tactical', title:'Attacking patterns — shadow movement', dur:15, sets:'', desc:'Study 3 attacking runs: overlap, third-man run, diagonal run in behind. Practice each in small space — shadow movement, no ball. Understand WHY each run creates space.', xp:25 },
    { id:'t5', pillar:'Physical', title:'Core & upper body circuit', dur:20, sets:'3 rounds', desc:'30 sec plank → 20 crunches → 15 push-ups → 10 mountain climbers → 20 leg raises → 10 tricep dips (chair). Rest 45 sec. Core = balance, shielding, aerial duels.', xp:30 },
  ]},
  '1-4': { rest: false, label: 'Thu', focus: 'Sprint Conditioning + Weak Foot + Plyometrics', tasks: [
    { id:'t1', pillar:'Physical', title:'Sprint intervals — Tabata protocol', dur:25, sets:'8 rounds', desc:'Sprint max effort in place 20 sec → rest 10 sec. 8 rounds = 4 min. Then: 5 × 30-sec lateral speed shuffles. Most football-specific cardio format. Gas tank builder.', xp:45 },
    { id:'t2', pillar:'Technical', title:'Weak foot dedicated session', dur:25, sets:'', desc:'100% weak foot only. Juggling (50) → sole rolls → inside/outside touches → wall passes or throw-and-receive. Most players skip this. Your weak foot is your hidden advantage.', xp:40 },
    { id:'t3', pillar:'Physical', title:'Explosive power — plyometrics', dur:20, sets:'4 rounds', desc:'5 box jumps (step/stair) → 10 broad jumps → 10 single-leg hops each side → 5 tuck jumps → 10 explosive push-ups. Rest 60 sec. Power = first to the ball, winning headers.', xp:35 },
    { id:'t4', pillar:'Tactical', title:'1v1 scenario mental simulation', dur:15, sets:'', desc:'Imagine 10 different 1v1 situations: winger vs fullback, striker vs CB, midfielder receiving under pressure. For each: decide first touch direction, body orientation, exit route. Verbalize out loud.', xp:20 },
    { id:'t5', pillar:'Mental', title:'Resilience & reset routine', dur:10, sets:'', desc:'Juggle for 3 minutes. When you drop: say "1-2-3, NEXT" out loud and restart with full focus. No frustration — just reset. This is a pre-set mental reset routine. Pros use it in matches.', xp:15 },
  ]},
  '1-5': { rest: false, label: 'Fri', focus: 'Control Under Fatigue + Shooting + Flexibility', tasks: [
    { id:'t1', pillar:'Physical', title:'Full body warm-up', dur:15, sets:'', desc:'Dynamic activation: arm swings, leg kicks, torso rotations, 20 jumping jacks, 10 squat jumps, inchworm walks (10), 5 burpees. 15 minutes, zero rest.', xp:20 },
    { id:'t2', pillar:'Technical', title:'Ball control under fatigue', dur:25, sets:'5 rounds', desc:'20 burpees → immediately 2 min ball mastery (sole rolls, toe taps). 5 rounds. Simulates receiving the ball after a sprint mid-match. Your control must hold when lungs are burning.', xp:45 },
    { id:'t3', pillar:'Technical', title:'Shooting technique — wall work', dur:20, sets:'', desc:'Mark target on wall. Technique: plant foot beside ball, locked ankle, strike through center, follow through. Drill: instep drive (30) → side-foot placement (30) → weak foot (20) → first-time volley (20).', xp:35 },
    { id:'t4', pillar:'Physical', title:'Flexibility & mobility', dur:15, sets:'', desc:'Hamstring (45 sec each) → hip flexor lunge (45 sec each) → quad (30 sec each) → groin butterfly (45 sec) → calf (30 sec each) → spine rotation → shoulder cross. Injury prevention + agility.', xp:20 },
    { id:'t5', pillar:'Tactical', title:'Set piece analysis', dur:10, sets:'', desc:'Choose: corners, free kicks, or throw-ins. Watch 5 pro examples. Identify: near-post run, far-post attack, second-ball role, defensive coverage. Set pieces decide matches.', xp:20 },
    { id:'t6', pillar:'Mental', title:'Weekly review & journal', dur:10, sets:'', desc:'Write: (1) Best technical moment this week (2) Hardest physical challenge (3) Tactical insight gained (4) Effort score 1–10. Champions review every week. Self-awareness is the upgrade.', xp:15 },
  ]},
  '1-6': { rest: false, label: 'Sat', focus: 'Endurance + Skills Creativity + Match Analysis', tasks: [
    { id:'t1', pillar:'Physical', title:'Long run / endurance session', dur:40, sets:'', desc:'40 min continuous at conversational pace. Outdoors or in-place stepping/jogging. Never stop. Week 1: pace doesn\'t matter — time on feet does. Football = 90+ minutes of constant movement.', xp:50 },
    { id:'t2', pillar:'Technical', title:'Skills combination challenge', dur:30, sets:'', desc:'String 5 skills in sequence (e.g. sole roll → step-over → Cruyff turn → inside touch → shoot). Perform 15 times. Create 3 different combos. Flair is built through personal creativity.', xp:45 },
    { id:'t3', pillar:'Tactical', title:'Full match — tactical notebook', dur:20, sets:'', desc:'Watch 20 min of elite match. Fill notebook: shape in possession, shape out of possession, pressing triggers, patterns of play, key link player. This is how coaches see the game.', xp:30 },
  ]},
  '1-7': { rest: true, label: 'Sun', tasks: [] },

  // ════ WEEK 2 ════
  '2-1': { rest: false, label: 'Mon', focus: 'Speed Work + Advanced Dribbling + 1v1 Confidence', tasks: [
    { id:'t1', pillar:'Physical', title:'Sprint activation — ladder protocol', dur:15, sets:'', desc:'No ladder needed. Mark 10 paces. High-step run forward and back (6 reps) → lateral shuffle (8 reps) → crossover step (6 reps) → two-footed hop forward-back (5 reps). Maximum speed.', xp:22 },
    { id:'t2', pillar:'Technical', title:'Advanced dribbling — Messi circuit', dur:25, sets:'', desc:'Roulette (25 each direction) → inside-outside combo dribble (30 reps) → body feint + accelerate (20) → fake shot + go (15) → La Croqueta (horizontal drag, 20 reps). These unlock 1v1 dominance.', xp:45 },
    { id:'t3', pillar:'Physical', title:'Acceleration & deceleration training', dur:20, sets:'5 rounds', desc:'Explosive acceleration 5 paces → hard stop → immediate direction change → 5 paces other way. 5 rounds of 8 reps. This replicates making & breaking runs in tight spaces.', xp:36 },
    { id:'t4', pillar:'Technical', title:'Receiving & turning — confined space', dur:20, sets:'', desc:'Simulate defender behind you. Receive an imaginary pass, use back-to-goal first touch to turn: (1) Cruyff away (2) Spin-turn (3) Step on-ball screen. 20 reps each. Own your receiving.', xp:30 },
    { id:'t5', pillar:'Mental', title:'Confidence & body language drill', dur:10, sets:'', desc:'Stand in front of mirror for 2 min — upright posture, chest out, calm eyes. Visualize dominating a 1v1. Then dribble with the ball for 5 min as if nothing can stop you. Confidence is trainable.', xp:18 },
    { id:'t6', pillar:'Tactical', title:'Pressing game — high press triggers', dur:10, sets:'', desc:'Study Liverpool\'s or City\'s high press (5 min clip). Identify: (1) the press trigger (GK pass, ball into feet) (2) who presses first (3) compactness of second line. Draw the shape.', xp:22 },
  ]},
  '2-2': { rest: false, label: 'Tue', focus: 'Power Intervals + Touch Series + Spatial Intelligence', tasks: [
    { id:'t1', pillar:'Physical', title:'Power warm-up — explosive chain', dur:15, sets:'', desc:'10 power skips → 10 bounding steps → 10 explosive squat-jumps → 10 lateral bounds → 10 drop-and-sprint-to-wall (or mark). Maximum intent on every rep.', xp:22 },
    { id:'t2', pillar:'Technical', title:'Touch series — right, left, both', dur:25, sets:'3 sets', desc:'R foot: 30 sole rolls, 30 inside rolls, 20 outside cuts. Repeat left. Weak foot deliberately gets extra: add 1 set. End with 5-min eyes-closed slow touches — trust your touch.', xp:38 },
    { id:'t3', pillar:'Physical', title:'Repeat sprint test — 6×30 sec', dur:20, sets:'6 reps', desc:'Sprint max in place 30 sec → 30 sec rest → repeat 6 times. Track mental effort rating 1–10 each rep. Maintaining output through rep 6 is the target. Football requires repeated sprints.', xp:40 },
    { id:'t4', pillar:'Tactical', title:'Spatial awareness — grid positioning', dur:15, sets:'', desc:'Draw a pitch on paper (simple). Trace 3 scenarios: (1) you receive ball wide, teammates\' positions (2) central zone, where to pass under pressure (3) late run into box — angles. Think in triangles.', xp:25 },
    { id:'t5', pillar:'Mental', title:'Pressure penalty session', dur:10, sets:'', desc:'Juggle for exactly 2 minutes. Then immediately: 20 knee-to-head headers. Final 3 min: max juggles. Keep score. Switching modes fast = match cognition under physical fatigue.', xp:20 },
    { id:'t6', pillar:'Technical', title:'Passing weight & disguise', dur:15, sets:'', desc:'Wall: pass to different spots on the wall (vary pace, angle). Practice disguise: look one way, pass another. No wall: place ball, check shoulder, pass to imaginary target. 50 reps each foot.', xp:28 },
  ]},
  '2-3': { rest: false, label: 'Wed', focus: 'Aerobic Benchmark + Heading + Tactical Creativity', tasks: [
    { id:'t1', pillar:'Physical', title:'30-min aerobic benchmark', dur:30, sets:'', desc:'30 min at an honest pace. Week 2 goal: cover more imaginary distance than week 1. Count sets of (2 min jog → 1 min medium pace → 30 sec sprint). How many complete sets can you do?', xp:45 },
    { id:'t2', pillar:'Technical', title:'Heading technique & confidence', dur:20, sets:'', desc:'Toss ball overhead, head back up (20 reps) → arch from neck, not head (key form cue) → heading for direction: aim left, aim right (15 each) → defensive clearing header (20) → attack header near/far post.', xp:32 },
    { id:'t3', pillar:'Tactical', title:'Counter-attack patterns', dur:15, sets:'', desc:'Counter-attacks win leagues. Study: transition moments (team wins ball) → first pass must be forward → wide player sprints into space → striker makes curved run. Practice the sprint in your space 10 times.', xp:28 },
    { id:'t4', pillar:'Physical', title:'Hip & shoulder mobility', dur:15, sets:'', desc:'90/90 hip stretch (60 sec each side) → pigeon pose (60 sec each) → thoracic spine rotation (10 each side) → shoulder rolls and circles (2 min) → side splits reach (60 sec). Mobility is hidden pace.', xp:22 },
    { id:'t5', pillar:'Mental', title:'Mindfulness — body scan', dur:10, sets:'', desc:'Lie flat. 10 slow breaths. Scan from feet to head: notice any tension, soreness, fatigue. Then 5 min of calm breathing with no distraction. Recovery begins in the nervous system.', xp:15 },
  ]},
  '2-4': { rest: false, label: 'Thu', focus: 'Plyometrics + Dead Ball Mastery + Tactical Scenarios', tasks: [
    { id:'t1', pillar:'Physical', title:'Plyometric progression — week 2', dur:25, sets:'4 rounds', desc:'5 single-leg box hops each leg → 8 depth drops (step off ledge, absorb landing) → 10 lateral bounds → 5 tuck jumps → 10 clap push-ups. Week 2 adds single-leg work. Land softly = absorbs force = protects knees.', xp:48 },
    { id:'t2', pillar:'Technical', title:'Dead ball delivery — free kicks', dur:25, sets:'', desc:'Mark a target 10-20 meters away. Practice: (1) driven low free kick — toe down, contact bottom half (2) dipping top corner — lean back, contact center (3) chip/lob — open foot. 30 attempts each type.', xp:42 },
    { id:'t3', pillar:'Tactical', title:'Zonal vs man-marking corners', dur:15, sets:'', desc:'Watch 3 corner routines each from a zonal and man-marking team. Note: who blocks runners (zonal), who tracks (man), where second ball drops. Design your own corner delivery routine for your team.', xp:27 },
    { id:'t4', pillar:'Mental', title:'Adversity reframe exercise', dur:10, sets:'', desc:'Write down your 3 biggest football failures. For each, write: (1) What I learned (2) How it made me stronger (3) What I\'d do differently. Champions don\'t avoid adversity — they mine it.', xp:18 },
    { id:'t5', pillar:'Physical', title:'Groin & quad deep stretch', dur:10, sets:'', desc:'Seated groin stretch hold 2 min → wide squat rock (30 sec) → lunge hold with quad grab (60 sec each) → single-leg deadlift stretch (30 sec each). Essential after plyometrics.', xp:16 },
  ]},
  '2-5': { rest: false, label: 'Fri', focus: 'Match Intensity Circuit + Composure on Ball', tasks: [
    { id:'t1', pillar:'Physical', title:'Match-intensity warm-up', dur:15, sets:'', desc:'This warm-up simulates pre-match protocol. Dynamic stretch 5 min → activation 5 min (high knees, shuffles, backpedal) → short bursts 5 min (sprint-stop-sprint). Arriving ready, not cold.', xp:22 },
    { id:'t2', pillar:'Technical', title:'Composure under pressure — technique', dur:25, sets:'', desc:'Interval format: 20 sec burpees → 40 sec precision dribbling. 8 rounds. The key: precise clean touches immediately after physical effort. This IS match composure. Every touch counts.', xp:48 },
    { id:'t3', pillar:'Technical', title:'Long passing & driven balls', dur:20, sets:'', desc:'Strike ball through center with full instep. Target: wall mark 15+ meters away. Driven pass (30) → lofted pass (lean back, 20) → half-volley drop-pass (20). Distance control is a weapon.', xp:36 },
    { id:'t4', pillar:'Physical', title:'Full body cool-down', dur:15, sets:'', desc:'10 min full stretch (hold each 45 sec): hamstring, hip flexor, quad, calf, groin, shoulder. 5 min slow breathing. Log: how do your legs feel 1–10? How focused were you 1–10?', xp:20 },
    { id:'t5', pillar:'Tactical', title:'Transition moments — film study', dur:10, sets:'', desc:'Find a match highlight focused on transitions. Watch 5 moments of defensive-to-offensive transition: first pass, run shapes, wide vs central outlet. Note: team with best transition wins most matches.', xp:22 },
    { id:'t6', pillar:'Mental', title:'Midweek journal + scoring', dur:10, sets:'', desc:'Rate yourself this week: Technical (1–10) → Physical (1–10) → Mental (1–10) → Tactical (1–10). Total score out of 40. Compare to Week 1. Where is the biggest improvement? Where is the gap?', xp:18 },
  ]},
  '2-6': { rest: false, label: 'Sat', focus: 'Endurance + Skills Test + Full Tactical Review', tasks: [
    { id:'t1', pillar:'Physical', title:'Week 2 endurance — distance upgrade', dur:45, sets:'', desc:'45 min continuous. Upgrade from Week 1: add 5 min, higher average pace. Structure: 3 min medium → 2 min fast → 30 sec sprint × 7 sets. Track completion and compare to last Saturday.', xp:58 },
    { id:'t2', pillar:'Technical', title:'Skills test — Week 2 benchmark', dur:30, sets:'', desc:'(1) Max consecutive juggles (new PB?) (2) 20 step-overs as fast as possible (3) Weak foot 30 solo passes to wall (4) Cruyff turn 10 reps, time yourself. Record results. You are your own benchmark.', xp:50 },
    { id:'t3', pillar:'Tactical', title:'Team tactical shape deep-dive', dur:20, sets:'', desc:'Pick a team. Study 15 min of their play. Map their shape: build-up from GK (short vs long) → midfield structure when pressing → front 3 spacing. What is their tactical identity? How does your natural game fit?', xp:30 },
  ]},
  '2-7': { rest: true, label: 'Sun', tasks: [] },

  // ════ WEEK 3 ════
  '3-1': { rest: false, label: 'Mon', focus: 'Power + Advanced Technical + Tactical Roles', tasks: [
    { id:'t1', pillar:'Physical', title:'Power complex warm-up', dur:15, sets:'', desc:'Contrast method: 5 heavy squats → 5 jump squats × 3. Generates post-activation potentiation — muscles fire 15% harder for the next 30 minutes. Revolutionary warm-up for explosiveness.', xp:25 },
    { id:'t2', pillar:'Technical', title:'Advanced ball mastery — Week 3', dur:25, sets:'', desc:'Rainbow flick practice (15 min) → Marseille turn (25 reps) → Neymar chop (20 reps) → outside-of-foot dribble circuit (30 reps). Week 3: every move needs to be match-usable, not just training-hall.', xp:50 },
    { id:'t3', pillar:'Physical', title:'Strength endurance — full circuit', dur:25, sets:'4 rounds', desc:'15 squat jumps → 12 single-leg lunges each → 20 push-ups → 15 pull-up substitute (row under table) → 10 nordic curl (feet under sofa) → 60 sec plank. Rest 60 sec. Week 3 = less rest, more load.', xp:48 },
    { id:'t4', pillar:'Tactical', title:'Your position role — deep analysis', dur:15, sets:'', desc:'Write a full tactical brief on YOUR position. Defensive duties, offensive duties, pressing triggers, spacing rules, when to hold shape vs join attack. Use a specific pro player as reference. 1 page.', xp:28 },
    { id:'t5', pillar:'Mental', title:'Visualization — adversity scenario', dur:10, sets:'', desc:'Visualize: you\'ve made an error (bad pass, missed chance). Slow heartbeat, reset, call for the ball, positive next action. Rehearse the exact mental recovery sequence 5 times. Errors don\'t define you — responses do.', xp:18 },
  ]},
  '3-2': { rest: false, label: 'Tue', focus: 'Match-Speed Dribbling + Explosive Agility', tasks: [
    { id:'t1', pillar:'Physical', title:'Explosive agility warm-up', dur:15, sets:'', desc:'T-drill in 4 square meters (4 turns, forward-lateral-back): 10 reps fast. 5-10-5 shuttle (5 paces right, 10 left, 5 right): 6 reps. Use socks on floor as markers. Compete with your previous time.', xp:25 },
    { id:'t2', pillar:'Technical', title:'Match-speed dribbling', dur:25, sets:'', desc:'Execute every dribble at match speed, not training pace. Slalom 10 × max speed → step-over then burst (20) → stop-and-go dribble (change pace 10 times over 15 paces, 8 reps) → 5v0 shadow attack run (10 reps).', xp:52 },
    { id:'t3', pillar:'Physical', title:'Repeat sprint endurance — Week 3', dur:25, sets:'8 rounds', desc:'40 sec max sprint in place → 20 sec full rest. 8 rounds. Week 3: rounds 7–8 must be same effort as rounds 1–2. Mental game kicks in. Use music if it helps. This is what matches demand.', xp:50 },
    { id:'t4', pillar:'Technical', title:'Shooting under pressure', dur:20, sets:'', desc:'10 burpees → 5 shooting reps (any technique). 6 rounds. Target the wall. First touch → set → shoot. You must land all 5 shots on target each round. If you miss: 3 extra burpees. Match pressure.', xp:45 },
    { id:'t5', pillar:'Mental', title:'Clarity — pre-session routine design', dur:10, sets:'', desc:'Design YOUR personal pre-training/pre-match routine: from waking up to first touch. Include: nutrition timing, music, stretch, mental phrase. Champions are creatures of habit. Write it, commit to it.', xp:18 },
  ]},
  '3-3': { rest: false, label: 'Wed', focus: 'Aerobic Threshold + Tactical Deep-Dive', tasks: [
    { id:'t1', pillar:'Physical', title:'Threshold run — working at discomfort', dur:35, sets:'', desc:'35 min at uncomfortable-but-sustainable pace. 3 min medium → 3 min hard (can\'t talk) → 1 min recovery. Repeat 5 sets. This builds the aerobic engine for high-tempo 90-minute output.', xp:52 },
    { id:'t2', pillar:'Tactical', title:'Build-up play from the back', dur:20, sets:'', desc:'Study a team that plays out from the back. Track: GK options, CB split positions, full-back roles in build-up, #6 (defensive mid) receiving position. Where are the passing triangles? Draw the first 3 passes of 5 attacks.', xp:35 },
    { id:'t3', pillar:'Technical', title:'Passing combinations — solo patterns', dur:20, sets:'', desc:'Tiki-taka style: 1-touch pass to wall, receive, 1-touch pass back. 50 consecutive. Then: pass → move 3 paces → receive return → pass again. Simulate triangles. Fast feet, quicker brain.', xp:38 },
    { id:'t4', pillar:'Mental', title:'Breathwork — box breathing', dur:10, sets:'', desc:'4-4-4-4: inhale 4 sec, hold 4, exhale 4, hold 4. 10 rounds. Used by Navy SEALs and elite athletes pre-performance. Drops cortisol, sharpens focus, steadies nervous system. Practice now so it works in matches.', xp:18 },
  ]},
  '3-4': { rest: false, label: 'Thu', focus: 'Max Strength + Tactical Set Pieces + Mental Edge', tasks: [
    { id:'t1', pillar:'Physical', title:'Max strength bodyweight — Week 3', dur:25, sets:'5 rounds', desc:'8 slow-tempo push-ups (3 sec down, 3 sec up) → 6 single-leg squats each → 10 decline push-ups (feet elevated) → 8 Bulgarian split squats each → 15 ab rollout (use ball). 45 sec rest. Controlled strength.', xp:52 },
    { id:'t2', pillar:'Tactical', title:'Set piece masterclass — design yours', dur:20, sets:'', desc:'Design a corner routine for your team. Include: taker, 2 runners (near/far post), 1 blocker, 1 holding for second ball, 1 covering defensively. Draw it. Then design a short corner variation. Present it like a coach.', xp:35 },
    { id:'t3', pillar:'Technical', title:'Volleys & half-volleys', dur:20, sets:'', desc:'Toss to yourself, volley at wall. Instep volley (20) → side-foot volley for placement (20) → half-volley from bounce (25) → weak-foot volley (15). Head steady, eye on contact point. Timing is everything.', xp:42 },
    { id:'t4', pillar:'Mental', title:'Elite visualization — full match script', dur:15, sets:'', desc:'Script a full 90 min in your mind. Warm-up, first touch, key moments, scoring, defending, full-time. Be specific about each sensation. 15 minutes of deep immersive visualization = brain rehearsal. Federer did this before every match.', xp:22 },
    { id:'t5', pillar:'Physical', title:'Recovery protocol — Week 3', dur:10, sets:'', desc:'Cold water on legs (or cold tap for 3 min) → legs-up-wall 5 min → full stretch: hamstring, hip flexor, quad, calf, shoulder. Body recovery is when gains are made. Treat it as training.', xp:18 },
  ]},
  '3-5': { rest: false, label: 'Fri', focus: 'Full High-Intensity Session + Decision Speed', tasks: [
    { id:'t1', pillar:'Physical', title:'High intensity match warm-up', dur:15, sets:'', desc:'Dynamic stretch + activation + progressive speed build. 5 min mobility → 5 min activation runs → 3 min of 10-sec max sprints × 6. Arrive at your session at 80% already.', xp:25 },
    { id:'t2', pillar:'Technical', title:'Decision-speed drill', dur:25, sets:'', desc:'Ball mastery for 2 min max speed → sudden stop → look left, look right, move to an imaginary option (simulate decision making at pace). 10 rounds. Then: receive ball, 1 touch to a direction, 3 paces sprint, shoot. 15 reps.', xp:52 },
    { id:'t3', pillar:'Physical', title:'HIIT — match simulation intervals', dur:25, sets:'10 rounds', desc:'45 sec max intensity (sprint, shuffle, jump, squat — rotate each round) → 15 sec rest. 10 rounds = 10 minutes of real-time. This replicates 90-minute sprint density compressed. Will feel like a final.', xp:55 },
    { id:'t4', pillar:'Tactical', title:'Opposition analysis exercise', dur:10, sets:'', desc:'Study a team known for defending deep (1-5-4-1 or park-the-bus). How do top teams break them down? Note: width, switching play, depth runs, set pieces, patience. Write: 5 ways to beat a low block.', xp:25 },
    { id:'t5', pillar:'Mental', title:'Week 3 progress — deep journal', dur:10, sets:'', desc:'Answer honestly: (1) What has genuinely improved? (2) What still needs work? (3) What would your manager say about you this week? (4) What will you do differently in Week 4? One goal only.', xp:18 },
  ]},
  '3-6': { rest: false, label: 'Sat', focus: 'Elite Endurance + Benchmark Tests + Tactical Debrief', tasks: [
    { id:'t1', pillar:'Physical', title:'Week 3 endurance — elite test', dur:50, sets:'', desc:'50 min. Week 3 target: complete 8 sets of (3 min working/1 min recovery) plus 2 min hard finish. Do not slow in the last 15 min. Finish the last 5 min at the same pace as the first 5. Mental test as much as physical.', xp:65 },
    { id:'t2', pillar:'Technical', title:'Full technical benchmark', dur:30, sets:'', desc:'Test and record: (1) Max consecutive juggles — new PB? (2) Weak foot — 20 wall passes, how many clean? (3) Dribbling speed — slalom 10 reps timed (4) Shooting accuracy — 10 attempts, how many on target? Log everything.', xp:55 },
    { id:'t3', pillar:'Tactical', title:'3-week tactical debrief', dur:20, sets:'', desc:'Review your tactical notes from all 3 weeks. What patterns have you studied most? What concepts do you understand deeply now that you didn\'t before? Write your personal tactical philosophy in 5 sentences.', xp:35 },
  ]},
  '3-7': { rest: true, label: 'Sun', tasks: [] },

  // ════ WEEK 4 ════
  '4-1': { rest: false, label: 'Mon', focus: 'Elite Activation + Masterclass Technical + Match Tactics', tasks: [
    { id:'t1', pillar:'Physical', title:'Elite match-day warm-up protocol', dur:15, sets:'', desc:'Exactly as you would prepare for a cup final. Foam roll (or self-massage) → dynamic mobility chain → progressive runs from 50% to 95% → activation bursts. From now on, every session is a final.', xp:28 },
    { id:'t2', pillar:'Technical', title:'Masterclass dribbling — elite touches', dur:30, sets:'', desc:'Combine all learned skills: Roulette → Cruyff → Neymar chop → Rainbow → Elastico. 10 min of flowing free-style sequence. Then: 1v0 attack in your space — full speed, change pace, change direction, finish.', xp:65 },
    { id:'t3', pillar:'Physical', title:'Power & speed complex', dur:25, sets:'5 rounds', desc:'5 squat jumps → 10 m sprint in place → 8 lateral explosive bounds → 5 tuck jumps → 30 sec rest. Week 4: every rep at 100%. No half-effort reps — they train your brain to accept mediocrity.', xp:58 },
    { id:'t4', pillar:'Tactical', title:'Week 4 tactical challenge — coach mode', dur:15, sets:'', desc:'Watch 15 min of elite match. Your task: predict what the manager says at half time. What needs to change? Which player is being targeted? What tactical switch is coming? Think like a manager.', xp:32 },
    { id:'t5', pillar:'Mental', title:'Identity statement — elite player mindset', dur:10, sets:'', desc:'Write: "I am a footballer who..." — fill 10 sentences. Describe your game at its peak, not your current level. Write it as if it\'s already true. Post it where you train. Your identity shapes every rep.', xp:22 },
  ]},
  '4-2': { rest: false, label: 'Tue', focus: 'Elite Agility + Weak Foot Mastery + Decision Making', tasks: [
    { id:'t1', pillar:'Physical', title:'Elite agility — reaction protocol', dur:20, sets:'', desc:'Set 3 marks (shoes, bottles). Number them. Randomly call numbers while running in place. React and touch that mark. 5 min reaction drill. Then: agility circuit 3 rounds (T-drill, shuffle, backpedal).', xp:35 },
    { id:'t2', pillar:'Technical', title:'Weak foot — match standard', dur:30, sets:'', desc:'Week 4: weak foot must perform at match standard. Juggling 100 consecutive target → free kicks × 20 → dribbling circuits → volleys → first touch control in 3 directions. Zero excuses. It\'s been 4 weeks.', xp:65 },
    { id:'t3', pillar:'Physical', title:'Repeat sprint — 90 min simulation', dur:25, sets:'12 rounds', desc:'12 rounds of: 40 sec hard → 20 sec rest. Simulates a compressed full match sprint density. Your decisions in round 10 should be as good as round 2. Train to think under physical fatigue.', xp:60 },
    { id:'t4', pillar:'Tactical', title:'Counter-press design', dur:15, sets:'', desc:'Counter-pressing (Gegenpressing): winning ball immediately after losing it. Design your team\'s counter-press trigger: who presses, who covers space, how long to counter-press before dropping. This is peak modern football intelligence.', xp:30 },
    { id:'t5', pillar:'Mental', title:'Performance focus ritual', dur:10, sets:'', desc:'Design a 5-min pre-performance ritual you will use before every match for life: (1) music track (2) a specific physical move (3) your mental phrase (4) breathing pattern (5) one image you visualize. Commit to it.', xp:22 },
  ]},
  '4-3': { rest: false, label: 'Wed', focus: 'Aerobic Peak + Full Tactical Blueprint', tasks: [
    { id:'t1', pillar:'Physical', title:'VO2 peak session', dur:40, sets:'', desc:'40 min: 2 min sprint effort → 2 min medium → repeat 10 times. Week 4 standard: sprint efforts at 95%+ every time. If you slow in the second half, redo the round. Compete with yourself mercilessly.', xp:65 },
    { id:'t2', pillar:'Tactical', title:'Full game tactical blueprint', dur:25, sets:'', desc:'Design your team\'s tactical identity for a full match: shape, pressing style, build-up plan, attacking patterns, set pieces attacking, set pieces defending. One page. Present it out loud. This is your football IQ peak.', xp:45 },
    { id:'t3', pillar:'Technical', title:'Wall passing combination patterns', dur:20, sets:'', desc:'1-touch wall combination × 50 → receive + turn + pass pattern × 30 → double-touch switch (inside-outside-pass) × 25 each foot. Fast, clean, accurate. Passing is the most used skill in football.', xp:45 },
    { id:'t4', pillar:'Mental', title:'Final week — champion\'s reflection', dur:10, sets:'', desc:'Answer: "If my week 1 self could see me now, what would they notice?" Write 3 specific technical improvements, 2 physical improvements, 1 mental improvement. You have become a different player. Notice it.', xp:22 },
  ]},
  '4-4': { rest: false, label: 'Thu', focus: 'Peak Strength + Full Technical + Tactical Mastery', tasks: [
    { id:'t1', pillar:'Physical', title:'Elite bodyweight strength — peak test', dur:30, sets:'5 rounds', desc:'10 explosive push-ups → 10 pistol squats each side → 12 plyo push-ups → 15 Nordic curl (feet under sofa) → 20 lateral bounds → 60 sec plank. Rest 45 sec. Every rep is intentional. This is your personal record session.', xp:65 },
    { id:'t2', pillar:'Technical', title:'30-minute freestyle technical', dur:30, sets:'', desc:'30 minutes of pure, unstructured technical play. No drill format. Just you and the ball. Express yourself. Combine everything you\'ve learned across 4 weeks. Invent things. This is where real footballers emerge.', xp:65 },
    { id:'t3', pillar:'Tactical', title:'Tactical masterclass — final exam', dur:20, sets:'', desc:'Watch 20 min of elite match. Now answer these like a coach: (1) What is each team\'s tactical identity? (2) Which player is most influential and why? (3) What would you change for the winning team at 60 mins? (4) How would you set up to beat them?', xp:45 },
    { id:'t4', pillar:'Mental', title:'Peak performance state — induction', dur:15, sets:'', desc:'Close eyes. 5 deep breaths. Recall the best football moment you have ever had. Where were you? What did it feel like? What did you hear? Stay in that feeling for 5 minutes. Then open eyes and train from that state.', xp:22 },
  ]},
  '4-5': { rest: false, label: 'Fri', focus: 'Full Match Simulation + Mental Peak', tasks: [
    { id:'t1', pillar:'Physical', title:'Full match warm-up — 20 min', dur:20, sets:'', desc:'Treat this as a cup final warm-up. Dynamic mobility → progressive running → activation → explosive bursts → ball work. Your body should be fully ready for match effort.', xp:30 },
    { id:'t2', pillar:'Technical', title:'90-minute match simulation', dur:60, sets:'', desc:'Simulate a full match solo: 45 min first half (alternate 5 min high-intensity: dribbling, shooting, juggling + 1 min walking rest) → 5 min half-time → 45 min second half same format. Push through discomfort in the last 20 min.', xp:80 },
    { id:'t3', pillar:'Tactical', title:'Post-match self-review', dur:10, sets:'', desc:'As if you just played a real match, write your match report: What went well? What was below standard? What tactical moment showed your growth? What do you want to work on? Real players do this.', xp:28 },
    { id:'t4', pillar:'Mental', title:'Letter to yourself in Week 1', dur:10, sets:'', desc:'Write a letter to Day 1 you. Describe what they\'re about to build, the hardest days, the breakthroughs, what surprised them, what they shouldn\'t skip. Be honest, be proud. This is your document of transformation.', xp:25 },
  ]},
  '4-6': { rest: false, label: 'Sat', focus: '30-Day Grand Finale — Test Everything', tasks: [
    { id:'t1', pillar:'Physical', title:'Grand finale endurance — 60 min', dur:60, sets:'', desc:'Your final endurance session. 60 minutes. Goal: do not slow down. Same intensity minute 55 as minute 5. If you manage this, your aerobic base is genuinely elite-level for home training. You earned this.', xp:80 },
    { id:'t2', pillar:'Technical', title:'30-Day Skills Grand Test', dur:35, sets:'', desc:'Record yourself. (1) Max juggling record (2) Dribbling sequence combining 5 skills (3) Best free kick technique (4) Weak foot 10 consecutive passes (5) Shooting: 10 attempts on target. Write final benchmark scores next to Week 1 scores.', xp:70 },
    { id:'t3', pillar:'Tactical', title:'30-Day tactical graduation', dur:20, sets:'', desc:'Final test: watch 15 min of live football with a notepad. Write your complete tactical analysis. Shape, pressing, transitions, key players, strengths, weakness. Compare this to your Week 1 notes. The difference is your tactical development.', xp:50 },
    { id:'t4', pillar:'Mental', title:'Elite certificate — your football identity', dur:15, sets:'', desc:'Write your official football CV as a player: your position, strengths developed over 30 days, tactics you understand, your mental edge. This is who you are now. The program is complete. The player continues.', xp:30 },
  ]},
  '4-7': { rest: true, label: 'Sun', tasks: [] },
};
